### PR TITLE
Release 1.0.6

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release version 1.0.6
| Type?         |
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by djoelleuch — COMMENTED** [review]
Hello @Hlavtox  ,
I 've checked this Release but i found some issues : 

**For PS 1.7.8.8 :** 

the module ps_bestsellers is well displayed on BO , the best-sales page displays the correct items but the block on FO home_page is bad displayed ! 

See the attached screen record below:

https://user-images.githubusercontent.com/115152460/220357498-59d6569e-a2f7-47e5-8091-fefb799fb06e.mp4

**For PS 8.0.0 :** 
The module is displayed on BO but on FO the block of  best sellers is hidden 

See the attached screen record below:

https://user-images.githubusercontent.com/115152460/220362969-db71cca0-4191-4c43-9110-e8743f52f549.mp4

**For PS 8.0.1 :** 
The module is displayed on BO but on FO the block of  best sellers is hidden 
See the attached screen record below:

[Untitled_ Feb 21 2023 11_40 AM (1).webm](https://user-images.githubusercontent.com/115152460/220363379-c400aa9b-2aef-469a-b97f-a69305939f93.webm)


Please check and feedback.

**Comment by Hlavtox** [comment]
@djoelleuch None of these issues can be cause by this release. You will have the same issues with 1.0.5.

**Review by djoelleuch — APPROVED** [review]
Hello @Hlavtox , 

I checked with 1.0.5 , there are the same issues  and not related to this release .
so it's QA  :heavy_check_mark: 

thanks

**Comment by ghost** [comment]
Thank you @Hlavtox && @djoelleuch

**Comment by SharakPL** [comment]
What's the hold up with this release? I see 1.0.6 is still just a draft 🤔

**Pull request merged**
